export const MODAL_ID = {
  CONFIRMATION_MODAL: 'CONFIRMATION_MODAL',
  ADD_SITE_MODAL: 'ADD_SITE_MODAL',
  EDIT_SITE_MODAL: 'EDIT_SITE_MODAL',
  IMPORT_SITES_MODAL: 'IMPORT_SITES_MODAL',
  ADD_PROMPT_MODAL: 'ADD_PROMPT_MODAL',
  EDIT_PROMPT_MODAL: 'EDIT_PROMPT_MODAL',
  ONBOARDING_MODAL: 'ONBOARDING_MODAL',
  SCRAPE_PROGRESS_MODAL: 'SCRAPE_PROGRESS_MODAL',
  CHANGELOG_MODAL: 'CHANGELOG_MODAL',
  EDIT_POSTING_MODAL: 'EDIT_POSTING_MODAL',
  DUPLICATE_POSTINGS_MODAL: 'DUPLICATE_POSTINGS_MODAL',
} as const
